### ISSUE TITLE
Missing SpellParts produces NPE instead of telling user that something was cracked.

### ISSUE THREAD

**Issue by AirBurn0** [RubilaxXxx/ArsMagica2-5#1]
[`getSkillName()`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L147) can easly produce null, but [`getDisplayName()`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L340) will ignore that and throw NPE. 
Usually this happens when user has spell with SpellPart that not included in current setup, like situations when you migrate from AM2 to AM2.5 or vice versa, or do something with AM2PG (install/uninstall it or some compat mods).
[`getSkillName()`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L147) method should respect [`missingShape`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L28), [`missingComponent`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L29C24-L29C41) and [`missingModifier`](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/spell/SkillManager.java#L30C24-L30C39).
Simle `==` check would be fine, I guess. Else, they all have id = -1.

AM2PG renders Missing SpellParts like red empty icons, I guess that also can be implemented in AM2.

**Comment by RubilaxXxx** [comment]
not sure to understand when the NPE happen. can you give me step to reproduce it

**Comment by AirBurn0** [comment]
> not sure to understand when the NPE happen. can you give me step to reproduce it

From player's perspective, it can be achieved like that:
Install AM2PG with Thaumcraft, Make some spell that contains, for example, (Outer Damage):
![image](https://github.com/user-attachments/assets/2806d5a2-5610-4fbf-8c16-c1f32bea9ecc)
Remove Thaumcraft, and try to look on spell:
![image](https://github.com/user-attachments/assets/f44f36aa-103e-483d-b84e-2c16a0e6135d)
That's all.
There is more simple ways to reproduce that bug without any manipulations with mods. Just change spell NBT tag to some unexisting spell Id, like that:
![image](https://github.com/user-attachments/assets/85a35e29-f1cd-40ee-8d48-609d0cc3503c)

Result will be the same.

**Comment by RubilaxXxx** [comment]
fixed

**Comment by AirBurn0** [comment]
> fixed

Would be better to get `Missing Shape` for missingShape, `Missing Component` for missingComponent and etc. instead of.. what it does now.
