### ISSUE TITLE
Downgrade NEI dependency

### ISSUE THREAD

**Issue by AirBurn0** [RubilaxXxx/ArsMagica2-5#11]
AM2.5 Requires GTNH NEI, but there is totally no point in having those.
Well, maybe TCLProject considers it more comfortable for developing, but backwards compatibility is more important, I guess.
Main reasons for it being incompatible is that good-old non-GTNH NEI [don't have](https://github.com/Chicken-Bones/NotEnoughItems/tree/master/src/codechicken/nei/recipe) [that class](https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/java/codechicken/nei/recipe/GuiRecipeTab.java).

**Comment by RubilaxXxx** [comment]
nope i know matrix wanted to downgrade aswell but making the stuff without the class added by GTNH  is a pain so i'm just gonna keep it like that and since GTNH NEI is on CF & modrinth i don't see any reason why you'd want to stay on old version
