### ISSUE TITLE
Remove CoFH core dependency

### ISSUE THREAD

**Issue by AirBurn0** [RubilaxXxx/ArsMagica2-5#12]
Basically needed only for [(RedstoneFluxDrain)](https://github.com/RubilaxXxx/ArsMagica2-5/blob/master/src/main/java/am2/spell/components/RedstoneFluxDrain.java) to work.
Just use
```java
if(Loader.isModLoaded('CoFHCore'))
```
before [this](https://github.com/RubilaxXxx/ArsMagica2-5/blob/b180c626bd35e9af066bed956b6838ca388a78bd/src/main/java/am2/spell/SkillTreeManager.java#L236) and [this](https://github.com/RubilaxXxx/ArsMagica2-5/blob/b180c626bd35e9af066bed956b6838ca388a78bd/src/main/java/am2/spell/SkillManager.java#L252) lines.
Also change `required-after:CoFHCore` to `after:CoFHCore` in [this line](https://github.com/RubilaxXxx/ArsMagica2-5/blob/b180c626bd35e9af066bed956b6838ca388a78bd/src/main/java/am2/AMCore.java#L66)

If there is NO RF, why the hell do we need RF drain spells, lol?

**Comment by RubilaxXxx** [comment]
already done in dev env 😄
