### ISSUE TITLE
Crash on server - am2/api/ILoreHelper

### ISSUE THREAD

**Issue by Thorium0** [RubilaxXxx/ArsMagica2-5#18]
My server crashes when using version 1.7.1 and up. 1.7.0 works fine. All versions work fine on my client. FYI server runs linux and client runs windows.
Crash report: [https://pastebin.com/cfxJLKnj](https://pastebin.com/cfxJLKnj)

**Comment by RubilaxXxx** [comment]
@AirBurn0 [this](https://github.com/AirBurn0/am2playground/issues/25) caused it :p, i guess i'll have to undo matrix stuff to fix it for good. for now i just removed it so server can launch.

**Comment by RubilaxXxx** [comment]
i'll make a release rq.

**Comment by AirBurn0** [comment]
> @AirBurn0 [this](https://github.com/AirBurn0/am2playground/issues/25) caused it :p, i guess i'll have to undo matrix stuff to fix it for good. for now i just removed it so server can launch.

Well, as expected. 
hat's why I'm saying that the Compendium system at the moment is somehow strange and not very logical.
