### ISSUE TITLE
AM2 Etherium PowerTypes.RegisterPowerType API makes no sense

### ISSUE THREAD

**Issue by AirBurn0** [RubilaxXxx/ArsMagica2-5#2]
First of all, we just have a mistake [here](https://github.com/RubilaxXxx/ArsMagica2-5/blob/5c1d300bc2a398ca05b799b9f5bd5e78ae9cdaad/src/main/java/am2/api/power/PowerTypes.java#L36):
```java
if (getByID(id) == NONE){
```
Method `getByID()` return `NONE` if there is no PowerType, but mistake in `RegisterPowerType()` wont allow to register something in this case.
Changing line to look like that:
```java
if (getByID(id) != NONE){
```
should solve the issue.

**Comment by RubilaxXxx** [comment]
done
